### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by freeNastran** [mrkearden/Thin-Wall-Cylinder-Buckling#1]
Hi,

Tried this on WIndows 10, but can't get an output vtu file. I don't have mumps, just changed to Banded.

Cheers

Cean

**Comment by mrkearden** [comment]
You would have to share the sif file

**Comment by freeNastran** [comment]
I just use your case.sif. Only change is:
`  Linear System Direct Method = Banded`

**Comment by mrkearden** [comment]
I just downloaded it and it is worked fine, the default location for the vtu file is in the mesh sub-folder.

**Comment by freeNastran** [comment]
Ah,  in the mesh sub-folder. All good. Thamks.
